### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Skyqula** [jaquadro/BigDoors#1] opened 2015-07-20 18:54 UTC
As the title says: crash when monsters die near/in/on a big door: http://pastebin.com/ddfm19Eq
Modlist: http://i.imgur.com/nPCZAUq.jpg

**Comment by jaquadro** [comment] 2015-12-03 05:30
@Ordinastie The issue is a bit dated, but I would think applies the same at least to carraige doors, since that was the code I modeled after.

Do you know if this is something that was resolved in MalisisCore since this summer?

**Comment by Ordinastie** [comment] 2015-12-03 14:54
Yes, it was resolved in a later update.

**Comment by jaquadro** [comment] 2015-12-03 14:56
Thanks for confirming!

**Closed as completed by jaquadro** 2015-12-03 14:56 UTC
